name: release

on:
  push:
    branches:
      - main

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Git setup
        uses: actions/checkout@v6

      - name: Node setup
        uses: actions/setup-node@v6
        with:
          node-version: latest
          package-manager-cache: false

      - name: pnpm setup
        uses: pnpm/action-setup@v5
        with:
          run_install: true

      - name: Publish packages
        run: pnpm exec changeset publish
